server:
  port: 9003
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security-basic
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
